#ifndef QSETTINGSDIALOG_GLOBAL_H
#define QSETTINGSDIALOG_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QSETTINGSDIALOG_LIBRARY)
#  define QSETTINGSDIALOGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QSETTINGSDIALOGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QSETTINGSDIALOG_GLOBAL_H
