#ifndef QSETTINGSDIALOGENGINE_GLOBAL_H
#define QSETTINGSDIALOGENGINE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QSETTINGSDIALOG_LIBRARY)
#  define QSETTINGSDIALOGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QSETTINGSDIALOGSHARED_IMPORT
#endif

#define outParam &

#endif // QSETTINGSDIALOGENGINE_GLOBAL_H
